version: '3'

services:
  app:
    container_name: dos
    build: .
    command: ["./node_modules/.bin/gulp", "bws"]
    environment:
      - NODE_ENV=development
      - DEBUG=democracyos*
      - MONGO_URL=mongodb://mongo/rosario
    links:
      - mongo
    ports:
      - 3000:3000
    volumes:
      - ./ext/bin:/usr/src/ext/bin
      - ./ext/config:/usr/src/ext/config
      - ./ext/lib:/usr/src/ext/lib
      - ./ext/package.json:/usr/src/ext/package.json
      - ./public:/usr/src/public
    tty: true

  mongo:
    container_name: dos-mongo
    image: mongo:3.2
    ports:
      - 27017:27017
    volumes:
      - ~/data:/data/db
